server:
  port: 8081 # 项目启动的端口

spring:
  profiles:
    active: dev # 默认激活 dev 本地开发环境
  servlet:
    multipart:
      max-file-size: 20MB # 限制单个上传文件的最大大小为 20MB。如果上传的文件大小超过这个值，将会被拒绝上传。
      max-request-size: 20MB # 限制整个上传请求的最大大小为 20MB。这包括所有上传文件的大小之和。如果请求总大小超过这个值，将会被拒绝

storage:
  type: minio # 对象存储类型